name: Github README

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate-snake-game-from-github-contribution-grid
    uses: Platane/snk@v3.2.0